on: [push]

name: AzureLoginSample

jobs:

  AzureLogin:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az vm list-ip-addresses --resource-group myResourceGroup --name myVM --query "[].virtualMachine.network.publicIpAddresses[].ipAddress" -o tsv