name: Terraform

on: [push]



jobs:

  AzureLogin:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

  TerraformInstall:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.6.1"
    - run: terraform --version

  TerraformInit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
    - run: terraform init
    - run: terraform apply --auto-approve

